### ISSUE TITLE
Location widget doesn't detect landmarks inside duties

### ISSUE THREAD

**Issue by SabSparrow** [una-xiv/umbra#82] opened 2024-05-10 19:40 UTC
The location widget doesn't seem to detect landmarks in some duties. For instance, if I enter Sastasha and enter the Empty Room near the start, it'll still show Wauling Pond. This is inconsistent with the behavior outside of duties.

**Comment by haroldiedema** [comment] 2024-05-10 22:06
This changed since the last update to increase performance to detect your current sub-territory. Previously I was continuously scanning for nearby map pins to determine what to show. Since the last update, it is using the territory name reported by the game itself instead.

The previous way had a lot of false-positives. In your example, Empty Room would still be shown even if you were in the corridor above it, just because the map pin would be closer by compared to the text location of the "Wauling Pond".

![image](https://github.com/una-xiv/umbra/assets/567518/cc8ceb6b-239e-4573-8337-cae45604ac6b)

Closing this, since it's currently working as intended.

**Closed by haroldiedema** 2024-05-10 22:06 UTC

**Comment by SabSparrow** [comment] 2024-05-11 13:53
No, this is an actual bug, I'm in the actual room and not the corridor. I've attached a screenshot that illustrates the issue, where I've just entered the Empty Room.
![empty room](https://github.com/una-xiv/umbra/assets/6931955/d6c2c5d2-440a-4377-8d6a-a04a55f615bf)

**Comment by SabSparrow** [comment] 2024-05-11 14:06
Ah, I was wrong about it applying only in duties, it seems to be an issue where it detects the first subsection and not the second... That wouldn't be an issue if the game used those consistently, but sometimes it's used for areas and sometimes it's used for landmarks. Here's an example of it happening in Middle La Noscea.
![zephyr](https://github.com/una-xiv/umbra/assets/6931955/d5f66c3b-e847-4541-80f8-46ec0f8f57e9)

**Comment by SabSparrow** [comment] 2024-05-11 14:12
I guess it may be desirable to prioritise the larger sections over landmarks, so maybe it's not a bug after all.
